# 빌드
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
COPY . ./
RUN npm install
RUN npm run build

# 파일 서빙
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
