# 빌드
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json ./
COPY . ./
RUN npm install
RUN npm run build

# Nginx로 서빙
FROM nginx:alpine

# React 빌드 결과물 복사
COPY --from=build /app/build /usr/share/nginx/html

# 커스텀 Nginx 설정 복사
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
